### PR TITLE
get rid of `*_filter` in favor of `*_action`

### PR DESCRIPTION
**Pull request by AndreiMotinga**

### CODE REVIEW

**Comment by tvdeyen** [comment]
Waits for #34 to be merged first.

**Review by tvdeyen — APPROVED** [review]
Changes are ok. Can be merged after #34 gets merged

**Comment by tvdeyen** [comment]
Could you please rebase with `master` now that #45 was merged? Thanks

**Comment by alepore** [comment]
This was done on #46

**Pull request closed without merging**
