### PR TITLE
Update locale_selector.html.erb.deface

### PR DESCRIPTION
**Pull request by OptimizmForever**
fix wrong attrs
append to ul#main-nav-bar
replace double quotes with single quotes

### CODE REVIEW

**Comment by SebAshton** [comment]
Think this duplicates #57

**Comment by OptimizmForever** [comment]
in current solidus 2.5 need append to ul#main-nav-bar and 'navbar-form' is class for form
correct me if i wrong

**Comment by SebAshton** [comment]
Ah! Apologies, so it does. In that case, it closes #57 😄 

Out of interest why the switch to single quotes in the HTML?

**Comment by OptimizmForever** [comment]
because in that strings not used interpolation

**Pull request closed without merging**
