### PR TITLE
fix #22

### LINKED ISSUE #22: uninitialized constant SolidusGlobalize::ControllerGlobalizeHelper::Fallbacks
GET /
Results in:
NameError in Spree::HomeController#index
uninitialized constant SolidusGlobalize::ControllerGlobalizeHelper::Fallbacks

In bundler/gems/solidus_globalize-1538996926f2/app/controllers/concerns/solidus_globalize/controller_globalize_helper.rb
```ruby
def globalize_fallbacks
  Fallbacks.config!
end
```

This only happens in environments that have:
```ruby
config.cache_classes = true
config.eager_load = true
```
## Setup
ruby 2.4.0
rails 5.0.2
solidus 2.1.0
solidus_auth_devise 1.6.2
solidusio-contrib/solidus_i18n@4abcb7a5747fffa4a3555d212d045d0eec19f0af
solidusio-contrib/solidus_globalize@1538996926f2a2cef69140c6c19c1fda0eb6a775
globalize/globalize@2fd4270b322f2dbc619441aacdfc8352caa183a9

Any suggestions how to resolve it?

### PR DESCRIPTION
**Pull request by AndreiMotinga**

### CODE REVIEW

**Comment by AndreiMotinga** [comment]
Should [configuration file](https://github.com/solidusio-contrib/solidus_globalize/blob/master/lib/solidus_globalize/configuration.rb) be added to `solidus_gemspec.rb` as well?

**Comment by AndreiMotinga** [comment]
Waits for #34 to be merged first.

**Comment by tvdeyen** [comment]
Could you please rebase with `master` now that #45 was merged? Also, please fix the commit message, so a future reader is able to understand was this commit is doing. Thanks

**Comment by mamhoff** [comment]
@AndreiMotinga will you address the feedback?

**Comment by mamhoff** [comment]
I again recommend reading https://chris.beams.io/posts/git-commit/ :)

**Pull request closed without merging**
